<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 static/bolsa_mexicana_de_valores.glb
-->

<script>
  import { Group, MeshStandardMaterial, DoubleSide } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/static/bolsa_mexicana_de_valores.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.hypar1002.geometry}
      material={new MeshStandardMaterial({ side: DoubleSide, color: 'white' })}
      rotation={[Math.PI, 0, Math.PI]}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
