<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 static/tiber2.glb -ts
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      IfcSlabencimera011: THREE.Mesh
      IfcSlabencimera012: THREE.Mesh
    }
    materials: {
      formaica_wood: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/static/tiber2.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcSlabencimera011.geometry}
      material={gltf.materials.formaica_wood}
      position={[4.35, 0.86, -4.4]}
      rotation={[Math.PI, 0, Math.PI]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcSlabencimera012.geometry}
      material={gltf.materials.formaica_wood}
      position={[5.55, 0.86, -4.4]}
      rotation={[Math.PI, 0, Math.PI]}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
