<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 static/tiber.glb --shadows --transform
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/tiber-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cylinder.geometry}
      material={gltf.materials.barandal}
      position={[-0.05, 0.75, -1]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cylinder001.geometry}
      material={gltf.materials.barandal}
      position={[-0.05, 0.5, -1]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={[0.5, 1, 0.5]}
    />
    <T.Group position={[3.74, 0.78, -3.67]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Entity_1_Mesh_0_1.geometry}
        material={gltf.materials.oscuro}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Entity_1_Mesh_0_2.geometry}
        material={gltf.materials['Coated Glossy']}
      />
    </T.Group>
    <T.Group position={[1.62, 0.83, -4.88]} rotation={[-Math.PI / 2, 0, 0.91]} scale={0.1}>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Curva_NURBS001_1.geometry}
        material={gltf.materials.oscuro}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Curva_NURBS001_2.geometry}
        material={gltf.materials['Glow Glass']}
      />
    </T.Group>
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube.geometry}
      material={gltf.materials.formaica_wood}
      position={[0.04, 2.3, -4.65]}
      rotation={[0, 0, -Math.PI / 2]}
    />
    <T.Group position={[2.13, 0, 16.11]}>
      <T.Mesh castShadow receiveShadow geometry={gltf.nodes.Geometry48.geometry} material={gltf.materials.Material24} />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Geometry48_1.geometry}
        material={gltf.materials.Material10}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Geometry48_2.geometry}
        material={gltf.materials.Material7}
      />
    </T.Group>
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cubo002.geometry}
      material={gltf.materials['Coated Glossy']}
      position={[0.81, 0.63, -4.83]}
      rotation={[-Math.PI, 0, -Math.PI / 2]}
      scale={[-0.31, -0.04, -0.29]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cubo003.geometry}
      material={gltf.materials['Coated Glossy']}
      position={[0.84, 0.63, -5.92]}
      rotation={[-Math.PI, 0.22, -Math.PI / 2]}
      scale={[-0.31, -0.04, -0.29]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cubo001.geometry}
      material={gltf.materials['Coated Glossy']}
      position={[2.79, 0.63, -4.81]}
      rotation={[0, 0, Math.PI / 2]}
      scale={[-0.31, -0.04, -0.29]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cubo004.geometry}
      material={gltf.materials['Coated Glossy']}
      position={[2.81, 0.63, -5.75]}
      rotation={[0, 0.17, Math.PI / 2]}
      scale={[-0.31, -0.04, -0.29]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube001.geometry}
      material={gltf.materials.formaica_wood}
      position={[0.14, 2.24, -4.65]}
      rotation={[0, 0, -Math.PI]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane001.geometry}
      material={gltf.materials.lona}
      position={[2.54, 1.06, -7.05]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Vert001.geometry}
      material={gltf.materials.oscuro}
      position={[1.24, 0, -4.51]}
      scale={[1, 1, 3.56]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Vert002.geometry}
      material={gltf.materials.oscuro}
      position={[1.2, 0, -5.51]}
      rotation={[0, -0.22, 0]}
      scale={[1, 1, 3.56]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Vert003.geometry}
      material={gltf.materials.oscuro}
      position={[2.36, 0, -5.13]}
      rotation={[Math.PI, 0, Math.PI]}
      scale={[1, 1, 3.56]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Vert004.geometry}
      material={gltf.materials.oscuro}
      position={[2.33, 0, -5.99]}
      rotation={[Math.PI, -0.17, Math.PI]}
      scale={[1, 1, 3.56]}
    />
    <T.Group position={[10.89, 0, -2.5]} rotation={[0, 0.98, 0]} scale={0.19}>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['0_mesh_004_1'].geometry}
        material={gltf.materials['verde.001']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['0_mesh_004_2'].geometry}
        material={gltf.materials.oscuro}
      />
    </T.Group>
    <T.Group position={[10.21, 0, -3.1]} rotation={[-Math.PI, 1.4, -Math.PI]} scale={0.15}>
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['0_mesh_004_1'].geometry}
        material={gltf.materials['verde.001']}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes['0_mesh_004_2'].geometry}
        material={gltf.materials.oscuro}
      />
    </T.Group>
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Entity_1_Mesh_0001.geometry}
      material={gltf.materials.oscuro}
      position={[7.33, 0.17, -4.72]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes['Low-Poly_Plant_001'].geometry}
      material={gltf.materials['verde.001']}
      position={[10.88, 0, -3]}
      rotation={[Math.PI, 0, Math.PI]}
      scale={1.23}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes['Low-Poly_Plant_'].geometry}
      material={gltf.materials.oscuro}
      position={[10.88, 0, -3]}
      rotation={[Math.PI, 0, Math.PI]}
      scale={1.23}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cubo026.geometry}
      material={gltf.materials['Coated Glossy']}
      position={[7.56, 0, -4.48]}
      rotation={[0, Math.PI / 2, 0]}
      scale={[0.36, 0.4, 0.36]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube003.geometry}
      material={gltf.materials['Coated Glossy']}
      position={[7.29, 0.6, -4.75]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane002.geometry}
      material={gltf.materials.spot_i}
      position={[0.19, 2.19, -5.9]}
      rotation={[0, 0, Math.PI / 2]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane003.geometry}
      material={gltf.materials.spot_i}
      position={[4.86, 2.19, -5.9]}
      rotation={[0, 0, -Math.PI / 2]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane004.geometry}
      material={gltf.materials.spot_i}
      position={[1.43, 2.19, -7.08]}
      rotation={[-Math.PI / 2, Math.PI / 2, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane005.geometry}
      material={gltf.materials.spot_i}
      position={[3.83, 2.19, -7.08]}
      rotation={[-Math.PI / 2, Math.PI / 2, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane006.geometry}
      material={gltf.materials.spot_i}
      position={[1.43, 2.19, -4.78]}
      rotation={[Math.PI / 2, Math.PI / 2, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Plane007.geometry}
      material={gltf.materials.spot_i}
      position={[3.83, 2.19, -4.78]}
      rotation={[Math.PI / 2, Math.PI / 2, 0]}
    />
    <T.Group position={[0.3, 0.79, 0.2]} rotation={[-Math.PI, 0, 0]}>
      <T.Mesh castShadow receiveShadow geometry={gltf.nodes.Cone009.geometry} material={gltf.materials.spot} />
      <T.Mesh castShadow receiveShadow geometry={gltf.nodes.Cone009_1.geometry} material={gltf.materials.spot_i} />
    </T.Group>
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Slab.geometry}
      material={gltf.materials.piso_azotea}
      position={[0, -0.2, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Wall001.geometry}
      material={gltf.materials.concreto}
      position={[-1.46, 0, 0.15]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Wall002.geometry}
      material={gltf.materials.concreto}
      position={[-0.15, 0, -7.13]}
      rotation={[0, -1.57, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Wall003.geometry}
      material={gltf.materials.concreto}
      position={[1.33, 0, -7.28]}
      rotation={[-Math.PI, 0, -Math.PI]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcWallWall004.geometry}
      material={gltf.materials.Material10}
      position={[5, 0, -7.28]}
      rotation={[0, -1.57, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcWallWall005.geometry}
      material={gltf.materials.malla_c}
      position={[5, 0, -4.98]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcWallWall006.geometry}
      material={gltf.materials.Unknown}
      position={[9.21, 0, -7.28]}
      rotation={[0, -1.57, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcWallWall007.geometry}
      material={gltf.materials.Unknown}
      position={[9.36, 0, -3.41]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcWallWall008.geometry}
      material={gltf.materials.Material10}
      position={[5, 0, -7.28]}
      rotation={[-Math.PI, 0, -Math.PI]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcWallWall009.geometry}
      material={gltf.materials.malla_c}
      position={[7.65, 0, -4.98]}
      rotation={[0, -1.57, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcWallWall010.geometry}
      material={gltf.materials.malla_c}
      position={[8.5, 0, -4.31]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcWallWall011.geometry}
      material={gltf.materials.malla_c}
      position={[11.23, 0, 0]}
      rotation={[0, 1.57, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcWallWall013.geometry}
      material={gltf.materials.Unknown}
      position={[5.15, 0, -4.28]}
      rotation={[-Math.PI, 0, -Math.PI]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcWallWall012.geometry}
      material={gltf.materials.Unknown}
      position={[5.3, 0, -3.55]}
      rotation={[-Math.PI, 0, -Math.PI]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcWallWall015.geometry}
      material={gltf.materials.Unknown}
      position={[5.15, 0, -4.28]}
      rotation={[0, -Math.PI / 2, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcWallWall014.geometry}
      material={gltf.materials.Unknown}
      position={[4.16, 0, -4.13]}
      rotation={[0, -1.57, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcBeamBeam005.geometry}
      material={gltf.materials.PTR}
      position={[0.19, 2.19, -7.13]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcBeamBeam007.geometry}
      material={gltf.materials.PTR}
      position={[2.69, 2.19, -7.13]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcColumnColumn004.geometry}
      material={gltf.materials.PTR}
      position={[0.2, 0, -7.1]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcColumnColumn006.geometry}
      material={gltf.materials.PTR}
      position={[0.2, 0, -4.7]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcColumnColumn003.geometry}
      material={gltf.materials.PTR}
      position={[4.9, 0, -7.1]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcColumnColumn005.geometry}
      material={gltf.materials.PTR}
      position={[4.9, 0, -4.94]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcBeamBeam004.geometry}
      material={gltf.materials.PTR}
      position={[4.93, 2.19, -7.11]}
      rotation={[Math.PI / 2, 0, Math.PI / 2]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcBeamBeam001.geometry}
      material={gltf.materials.PTR}
      position={[4.9, 2.19, -4.67]}
      rotation={[Math.PI / 2, 0, -Math.PI]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcBeamBeam006.geometry}
      material={gltf.materials.PTR}
      position={[0.16, 2.19, -4.69]}
      rotation={[Math.PI / 2, 0, -Math.PI / 2]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcColumnColumn007.geometry}
      material={gltf.materials.PTR}
      position={[6.53, 0, -4.34]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcColumnColumn009.geometry}
      material={gltf.materials.PTR}
      position={[5.33, 0, -4.34]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcColumnColumn012.geometry}
      material={gltf.materials.PTR}
      position={[6.53, 0, -4.88]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcColumnColumn010.geometry}
      material={gltf.materials.PTR}
      position={[5.33, 0.79, -4.34]}
      rotation={[0, 0, -Math.PI / 2]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcColumnColumn014.geometry}
      material={gltf.materials.PTR}
      position={[5.33, 0.79, -2.91]}
      rotation={[-Math.PI / 2, Math.PI / 2, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcColumnColumn028.geometry}
      material={gltf.materials.PTR}
      position={[4.15, 0.79, -4.88]}
      rotation={[0, 0, -Math.PI / 2]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcColumnColumn030.geometry}
      material={gltf.materials.PTR}
      position={[4.18, 0.79, -4.88]}
      rotation={[Math.PI / 2, -Math.PI / 2, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcColumnColumn031.geometry}
      material={gltf.materials.PTR}
      position={[4.18, 0, -4.88]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcColumnColumn032.geometry}
      material={gltf.materials.PTR}
      position={[4.73, 0, -4.88]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcColumnColumn033.geometry}
      material={gltf.materials.PTR}
      position={[4.19, 0, -2.88]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcColumnColumn034.geometry}
      material={gltf.materials.PTR}
      position={[5.33, 0, -2.88]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcColumnColumn035.geometry}
      material={gltf.materials.PTR}
      position={[4.22, 0.79, -2.88]}
      rotation={[0, 0, -Math.PI / 2]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.IfcColumnColumn008.geometry}
      material={gltf.materials.PTR}
      position={[6.53, 0.79, -3.45]}
      rotation={[-Math.PI / 2, Math.PI / 2, 0]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Wall004.geometry}
      material={gltf.materials.boho}
      position={[9.23, 0, 0.25]}
      rotation={[-Math.PI, 0, -Math.PI]}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
